#BIODATA IDOLAKU
print('========================================================')
print('|                    PROGRAM BIODATA                   |')
print('========================================================')
print('|                    Biodata Idolaku                   |')
print('========================================================')
print('| Nama           = Stephen Curry                       |')
print('| Gender         = Male                                |')
print('| TTL            = Akron,Ohio, 14 MARET 1988           |')
print('| Kebangsaan     = Amerika Serikat                     |')
print('| Usia           =  34 Tahun                           |')
print('| Tinggi         = 191 cm                              |')
print('| Berat_Badan    = 86 kg                               |')
print('| Perguan_Tinggi = Davidson (2006-2009)                |')
print('| Draft_NBA      = 2009/Babak : 1/Pick : 7             |')
print('| Pekerjaan      = Pebasket Profesional                |')
print('| Liga           = NBA                                 |')
print('| Posisi         = Point Guard,Shooting Guard          |')
print('| Karier_Bermain = 2009-Sekarang                       |')
print('| Klub           = Golden State Warriors               |')
print('========================================================')

